# Build application on release creation and attach produced files to the Release.
name: Container Dashbaord Build Validation

on:
  workflow_dispatch:
    inputs:

  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-26, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build Packages
        run: npm run make
